{"name": "Sicilian Dragon: The Real Deal! Part 1: Understanding The Dragon", "author": "Chris Ward", "url": "https://shop.chessbase.com/en/products/ward_sicilian_dragon_part_1", "previewURL": ["//youtube.com/embed/n52ojzDiaOI"], "price": ["29.65", "29.65"], "timeHours": ["5", "5", "5", "5"], "timeMinutes": "20"}
{"name": "Fritz Powerbook 2021", "author": "", "url": "https://shop.chessbase.com/en/products/powerbook_2021", "previewURL": [], "price": ["69.31", "69.31"], "timeHours": [], "timeMinutes": "60"}
{"name": "Navigating the Ruy Lopez Vol.2", "author": "Fabiano Caruana", "url": "https://shop.chessbase.com/en/products/fabiano_caruana_navigating_the_ruy_lopez_vol2", "previewURL": ["//youtube.com/embed/Y_EnobzrRqI"], "price": ["29.65", "29.65"], "timeHours": ["5", "5", "5", "5"], "timeMinutes": "52"}
{"name": "An Attacking Repertoire with 1.d4 Vol.3", "author": "Nicholas Pert", "url": "https://shop.chessbase.com/en/products/pert_attacking_repertoire_with_d4_vol_3", "previewURL": ["//youtube.com/embed/JeJ8Bl31m98"], "price": ["29.65", "29.65"], "timeHours": ["5", "5", "5", "5"], "timeMinutes": null}
{"name": "Navigating the Ruy Lopez Vol.1", "author": "Fabiano Caruana", "url": "https://shop.chessbase.com/en/products/fabiano_caruana_navigating_the_ruy_lopez_vol1", "previewURL": ["//youtube.com/embed/Y_EnobzrRqI"], "price": ["29.65", "29.65"], "timeHours": ["5", "5", "5", "5"], "timeMinutes": null}
{"name": "The English Opening - Tactic and Strategy Toolbox", "author": "Mihail Marin", "url": "https://shop.chessbase.com/en/products/marin_english_tactic_strategy_toolbox", "previewURL": ["//youtube.com/embed/aoTFxki-yms"], "price": ["29.65", "29.65"], "timeHours": ["5", "5", "5", "5"], "timeMinutes": "30"}
{"name": "Marin's English Love -Vol. 1, Vol2 and Tactic and Strategy Toolbox", "author": "Mihail Marin", "url": "https://shop.chessbase.com/en/products/marin_english_vol1_vol2_strategy_toolbox", "previewURL": ["//youtube.com/embed/oq5CyU0pQ0w"], "price": ["79.23", "79.23"], "timeHours": ["5", "5", "5", "5"], "timeMinutes": "13"}
{"name": "Winning with the King's Indian Attack, King's Indian: A modern approach + Kings Indian Powerbook & Powerbase", "author": "Victor Bologan", "url": "https://shop.chessbase.com/en/products/bologan_the_kings_indian_bundle", "previewURL": ["//youtube.com/embed/8PK1we83Ehk"], "price": ["69.31", "69.31"], "timeHours": ["7", "7", "7", "7"], "timeMinutes": "27"}
{"name": "The Exciting Budapest Gambit", "author": "Simon Williams", "url": "https://shop.chessbase.com/en/products/williams_the_budapest_gambit", "previewURL": ["//youtube.com/embed/3c4vnpCvESg"], "price": ["29.65", "29.65"], "timeHours": ["6", "6", "6", "6"], "timeMinutes": "16"}
{"name": "Navigating the Ruy Lopez Vol.3", "author": "Fabiano Caruana", "url": "https://shop.chessbase.com/en/products/fabiano_caruana_navigating_the_ruy_lopez_vol3", "previewURL": ["//youtube.com/embed/Y_EnobzrRqI"], "price": ["29.65", "29.65"], "timeHours": ["5", "5", "5", "5"], "timeMinutes": "26"}
{"name": "Navigating the Ruy Lopez Vol.1-3", "author": "Fabiano Caruana", "url": "https://shop.chessbase.com/en/products/fabiano_caruana_navigating_the_ruy_lopez_vol1-3", "previewURL": ["//youtube.com/embed/Y_EnobzrRqI"], "price": ["79.23", "79.23"], "timeHours": ["16", "16", "16", "16"], "timeMinutes": "20"}
{"name": "Attacking Repertoire with 1.d4! Vol. 1 - 3", "author": "Nicholas Pert", "url": "https://shop.chessbase.com/en/products/pert_attacking_repertoire_with_d4_vol_1_vol_2_vol_3", "previewURL": [], "price": ["79.23", "79.23"], "timeHours": ["5", "5", "5", "5"], "timeMinutes": "35"}
