{"url": "https://www.chess.com/lessons/daniil-dubovs-amazing-opening-ideas"}
{"url": "https://www.chess.com/lessons/the-sicilian-nimzowitsch-variation"}
{"url": "https://www.chess.com/lessons/tips-and-tricks-of-the-london-system"}
{"url": "https://www.chess.com/lessons/how-to-win-with-the-ruy-lopez-exchange-variation"}
{"url": "https://www.chess.com/lessons/attack-in-the-ruy-lopez-with-5-d4"}
{"url": "https://www.chess.com/lessons/learn-the-ruy-lopez-marshall-attack"}
{"url": "https://www.chess.com/lessons/learn-the-semi-slav-defense"}
{"url": "https://www.chess.com/lessons/learn-the-ruy-lopez-berlin-defense"}
{"url": "https://www.chess.com/lessons/learn-the-kings-indian-defense"}
{"url": "https://www.chess.com/lessons/learn-the-sicilian-sveshnikov"}
{"url": "https://www.chess.com/lessons/guide-to-the-alekhines-defense"}
{"url": "https://www.chess.com/lessons/learn-the-sicilian-najdorf"}
{"url": "https://www.chess.com/lessons/learn-to-play-the-tarrasch-defense"}
{"url": "https://www.chess.com/lessons/learn-to-play-the-scotch-game"}
{"url": "https://www.chess.com/lessons/the-fighting-dragon"}
{"url": "https://www.chess.com/lessons/how-to-play-the-philidor-defense"}
{"url": "https://www.chess.com/lessons/pirc-defense-for-black"}
{"url": "https://www.chess.com/lessons/pirc-defense-for-white"}
{"url": "https://www.chess.com/lessons/secrets-of-the-english-attack"}
{"url": "https://www.chess.com/lessons/the-complete-english-defense"}
{"url": "https://www.chess.com/lessons/the-belgrade-gambit"}
{"url": "https://www.chess.com/lessons/how-to-play-the-trompowsky"}
{"url": "https://www.chess.com/lessons/the-complete-queens-gambit-declined"}
{"url": "https://www.chess.com/lessons/spicy-gambits"}
{"url": "https://www.chess.com/lessons/the-complete-caro"}
{"url": "https://www.chess.com/lessons/the-benoni-and-its-tactics"}
{"url": "https://www.chess.com/lessons/why-simon-loves-the-sicilian"}
{"url": "https://www.chess.com/lessons/why-simon-loves-the-french"}
{"url": "https://www.chess.com/lessons/ruy-lopez-lessons"}
{"url": "https://www.chess.com/lessons/spicy-openings-the-max-lange-attack"}
{"url": "https://www.chess.com/lessons/beating-the-anti-sicilians"}
{"url": "https://www.chess.com/lessons/complete-scotch-2-mieses-theory-middlegame"}
{"url": "https://www.chess.com/lessons/understanding-the-london-system"}
{"url": "https://www.chess.com/lessons/the-classical-dutch"}
{"url": "https://www.chess.com/lessons/crush-with-the-kings-gambit"}
{"url": "https://www.chess.com/lessons/winning-with-the-chigorin"}
{"url": "https://www.chess.com/lessons/attack-with-the-catalan"}
{"url": "https://www.chess.com/lessons/play-the-budapest"}
{"url": "https://www.chess.com/lessons/london-system-for-the-busy-chess-player"}
{"url": "https://www.chess.com/lessons/nakamuras-kings-indian-defense"}
{"url": "https://www.chess.com/lessons/spicy-openings-the-evans-gambit"}
{"url": "https://www.chess.com/lessons/slay-the-slav-with-the-boor-attack"}
{"url": "https://www.chess.com/lessons/exploiting-opening-errors-2"}
{"url": "https://www.chess.com/lessons/exploiting-opening-errors-3"}
{"url": "https://www.chess.com/lessons/exploiting-typical-opening-errors"}
{"url": "https://www.chess.com/lessons/slaying-the-sicilian-kingside-storms"}
{"url": "https://www.chess.com/lessons/understanding-the-sicilian-dragon"}
{"url": "https://www.chess.com/lessons/defeating-pet-openings"}
{"url": "https://www.chess.com/lessons/now-what"}
{"url": "https://www.chess.com/lessons/understanding-the-colle-zukertort"}
{"url": "https://www.chess.com/lessons/a-kaleidoscope-of-openings"}
